version: "3.7"
services:
  app:
    build:
      args:
        user: sf #as in the host machine
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: php-demo-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - php-demo-app

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - php-demo-app
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    networks:
      - php-demo-app

networks:
  php-demo-app:
    driver: bridge
